export const otBooks = [
  'Genesis',
  'Exodus',
  'Leviticus',
  'Numbers',
  'Deuteronomy',
  'Joshua',
  'Judges',
  'Ruth',
  '1 Samuel',
  '2 Samuel',
  '1 Kings',
  '2 Kings',
  '1 Chronicles',
  '2 Chronicles',
  'Ezra',
  'Nehemiah',
  'Esther',
  'Job',
  'Psalms',
  'Proverbs',
  'Ecclesiastes',
  'Song of Songs',
  'Isaiah',
  'Jeremiah',
  'Lamentations',
  'Ezekiel',
  'Daniel',
  'Hosea',
  'Joel',
  'Amos',
  'Obadiah',
  'Jonah',
  'Micah',
  'Nahum',
  'Habakkuk',
  'Zephaniah',
  'Haggai',
  'Zechariah',
  'Malachi'
];

export const ntBooks = [
  'Matthew',
  'Mark',
  'Luke',
  'John',
  'Acts',
  'Romans',
  '1 Corinthians',
  '2 Corinthians',
  'Galatians',
  'Ephesians',
  'Philippians',
  'Colossians',
  '1 Thessalonians',
  '2 Thessalonians',
  '1 Timothy',
  '2 Timothy',
  'Titus',
  'Philemon',
  'Hebrews',
  'James',
  '1 Peter',
  '2 Peter',
  '1 John',
  '2 John',
  '3 John',
  'Jude',
  'Revelation'
];

export const getBook =  {
  '1 Chronicles': () => require('../../bible/1_Chronicles.json'),
  '1 Corinthians': () => require('../../bible/1_Corinthians.json'),
  '1 John': () => require('../../bible/1_John.json'),
  '1 Kings': () => require('../../bible/1_Kings.json'),
  '1 Peter': () => require('../../bible/1_Peter.json'),
  '1 Samuel': () => require('../../bible/1_Samuel.json'),
  '1 Thessalonians': () => require('../../bible/1_Thessalonians.json'),
  '1 Timothy': () => require('../../bible/1_Timothy.json'),
  '2 Chronicles': () => require('../../bible/2_Chronicles.json'),
  '2 Corinthians': () => require('../../bible/2_Corinthians.json'),
  '2 John': () => require('../../bible/2_John.json'),
  '2 Kings': () => require('../../bible/2_Kings.json'),
  '2 Peter': () => require('../../bible/2_Peter.json'),
  '2 Samuel': () => require('../../bible/2_Samuel.json'),
  '2 Thessalonians': () => require('../../bible/2_Thessalonians.json'),
  '2 Timothy': () => require('../../bible/2_Timothy.json'),
  '3 John': () => require('../../bible/3_John.json'),
  'Acts': () => require('../../bible/Acts.json'),
  'Amos': () => require('../../bible/Amos.json'),
  'Colossians': () => require('../../bible/Colossians.json'),
  'Daniel': () => require('../../bible/Daniel.json'),
  'Deuteronomy': () => require('../../bible/Deuteronomy.json'),
  'Ecclesiastes': () => require('../../bible/Ecclesiastes.json'),
  'Ephesians': () => require('../../bible/Ephesians.json'),
  'Esther': () => require('../../bible/Esther.json'),
  'Exodus': () => require('../../bible/Exodus.json'),
  'Ezekiel': () => require('../../bible/Ezekiel.json'),
  'Ezra': () => require('../../bible/Ezra.json'),
  'Galatians': () => require('../../bible/Galatians.json'),
  'Genesis': () => require('../../bible/Genesis.json'),
  'Habakkuk': () => require('../../bible/Habakkuk.json'),
  'Haggai': () => require('../../bible/Haggai.json'),
  'Hebrews': () => require('../../bible/Hebrews.json'),
  'Hosea': () => require('../../bible/Hosea.json'),
  'Isaiah': () => require('../../bible/Isaiah.json'),
  'James': () => require('../../bible/James.json'),
  'Jeremiah': () => require('../../bible/Jeremiah.json'),
  'Job': () => require('../../bible/Job.json'),
  'Joel': () => require('../../bible/Joel.json'),
  'John': () => require('../../bible/John.json'),
  'Jonah': () => require('../../bible/Jonah.json'),
  'Joshua': () => require('../../bible/Joshua.json'),
  'Jude': () => require('../../bible/Jude.json'),
  'Judges': () => require('../../bible/Judges.json'),
  'Lamentations': () => require('../../bible/Lamentations.json'),
  'Leviticus': () => require('../../bible/Leviticus.json'),
  'Luke': () => require('../../bible/Luke.json'),
  'Malachi': () => require('../../bible/Malachi.json'),
  'Mark': () => require('../../bible/Mark.json'),
  'Matthew': () => require('../../bible/Matthew.json'),
  'Micah': () => require('../../bible/Micah.json'),
  'Nahum': () => require('../../bible/Nahum.json'),
  'Nehemiah': () => require('../../bible/Nehemiah.json'),
  'Numbers': () => require('../../bible/Numbers.json'),
  'Obadiah': () => require('../../bible/Obadiah.json'),
  'Philemon': () => require('../../bible/Philemon.json'),
  'Philippians': () => require('../../bible/Philippians.json'),
  'Proverbs': () => require('../../bible/Proverbs.json'),
  'Psalms': () => require('../../bible/Psalms.json'),
  'Revelation': () => require('../../bible/Revelation.json'),
  'Romans': () => require('../../bible/Romans.json'),
  'Ruth': () => require('../../bible/Ruth.json'),
  'Song of Songs': () => require('../../bible/Song_of_Songs.json'),
  'Titus': () => require('../../bible/Titus.json'),
  'Zechariah': () => require('../../bible/Zechariah.json'),
  'Zephaniah': () => require('../../bible/Zephaniah.json')
};
